[runtime]
image_name = "sandbox"
image_tag = "latest"
container_name = "tester_runtime"
network_name = "lab_net"
mem_limit = "1g"

[agent]
source = "GOOGLE"
model_path = "./models/ggml-model-q4_0.bin"
google_model = "gemini-2.5-flash-lite"
openai_model = "gpt-4o-mini"